### ISSUE TITLE
Use option 'accept-buildout-test releases = true' the buildout to avoid problems with versions of recipes.

### ISSUE THREAD

**Issue by idgserpro** [collective/buildout.plonetest#16]
The version of zc.buildout used by Plone 4 is 1.7.1. In this version, by default, buildout uses final versions when installing recipes. But time to install the 'part' that uses the recipe it uses non-final versions (a1, b1, etc.).This causes inconsistencies if non-final version is not compatible with the final version.

An example this inconsistency is the plone.recipe.codeanalysis recipe. If you do not pining the plone.recipe.codeanalysis the buildout will download the final version (currently 1.1.1) when installing the recipe, but in time to install the part 'code-analysis', it will download the non-final version (2.0b1 currently). To see use in buildout:

```buildout
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg
    https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg
...
```
and do:

```shell
rm -rf /path/to/download-cache/dist/plone.recipe.codeanalysis-*
rm -rf /path/to/eggs-directory/eggs/plone.recipe.codeanalysis-*
./bin/buildout
```
The result is:

    /home/user/cache-python/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
    Develop: '/home/user/sites/mysite/zeocluster/src/myproduct/.'
    /home/user/cache-python/eggs/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '1.1.1.dev' to '1.1.1.dev0'
    Getting distribution for 'plone.recipe.codeanalysis'.
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Got plone.recipe.codeanalysis 1.1.1.
    Uninstalling code-analysis.
    Unused options for buildout: 'package-min-coverage'.
    Updating instance.
    Updating test.
    Installing code-analysis.
    Getting distribution for 'plone.recipe.codeanalysis'.
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '**/.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '**/__pycache__' found anywhere in distribution
    Got plone.recipe.codeanalysis 2.0b1.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/flake8'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-flake8'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-jshint'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-jscs'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-csslint'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-zptlint'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-deprecated-aliases'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-clean-lines'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-pep3101'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-imports'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-debug-statements'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-find-untranslated'.
    Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-hasattr'.
    Unable to create git pre-commit hook, this does not seem to be a git repository.
    Updating omelette.
    omelette: (While processing egg setuptools) Package '_markerlib' is zipped.  Skipping.
    omelette: (While processing egg setuptools) Package 'easy_install' is zipped.  Skipping.
    omelette: (While processing egg setuptools) Package 'pkg_resources' is zipped.  Skipping.
    omelette: (While processing egg setuptools) Package 'setuptools' is zipped.  Skipping.
    Updating node.

Note that it downloads the two versions (1.1.1 when installing the recipe, and  2.0b1 to install the part 'code-analysis').These two versions are incompatible.

The source code-analysis-clean-lines is something like:

```python
#!/home/user/pythons/python279-virtualenv/bin/python

import sys
sys.path[0:0] = [
    '/home/user/cache-python/eggs/plone.recipe.codeanalysis-2.0b1-py2.7.egg',
    '/home/user/cache-python/eggs/zc.recipe.egg-1.3.2-py2.7.egg',
    '/home/user/cache-python/eggs/zc.buildout-1.7.1-py2.7.egg',
    '/home/user/cache-python/eggs/setuptools-18.0.1-py2.7.egg',
    '/home/user/cache-python/eggs/flake8-2.4.1-py2.7.egg',
    '/home/user/cache-python/eggs/check_manifest-0.25-py2.7.egg',
    '/home/user/cache-python/eggs/mccabe-0.3.1-py2.7.egg',
    '/home/user/cache-python/eggs/pep8-1.5.7-py2.7.egg',
    '/home/user/cache-python/eggs/pyflakes-0.8.1-py2.7.egg',
    ]


import plone.recipe.codeanalysis

if __name__ == '__main__':
    sys.exit(plone.recipe.codeanalysis.code_analysis_clean_lines({...
```
Note that the egg used in sys.path is ```plone.recipe.codeanalysis-2.0b1-py2.7.egg```. But ```plone.recipe.codeanalysis.code_analysis_clean_lines``` method does not exist in version 2.0b1 but in 1.1.1. When you run a ```./bin/code-analysis-clean-lines``` get the error:

    AttributeError: 'module' object has no attribute 'code_analysis_clean_lines'

This occurs in other code analysis scripts. And this inconsistency may occur in other recipes.

My suggestion is to use the option:

[accept-buildout-test-releases = true](https://pypi.python.org/pypi/zc.buildout/1.7.1#automatic-buildout-updates)

the buildout. With ```accept-buildout-test-releases = true``` buildout will download the non-final version when installing recipes, avoiding inconsistencies.

Plone 5 uses zc.buildout 2.2.5. In this version, the inconsistency above does not occur. However, by default, it downloads the final version (in the case above, 1.1.1). To use the no-final version, we would have to use the option:

[prefer-final = false](https://pypi.python.org/pypi/zc.buildout/2.2.5#predefined-buildout-options)

**Comment by idgserpro** [comment]
@hvelarde opinion?

**Comment by hvelarde** [comment]
I think I'm :-1:  for this one; the `prefer-final` option exists in both versions and you can change that in your own configuration extending from these ones.

`accept-buildout-test-releases` controls the behavior of the build system itself and it doesn't exist in Buildout 2.0.

starting with Plone 5.0 configuration, we can include `show-picked-versions = true` to be very explicit on what packages are missing pinning.

**Comment by idgserpro** [comment]
@hvelarde ```prefer-final``` doesn't work in zc.buildout 1.7.1. if I have in my buildout:

```buildout
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg
    https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg

prefer-final = false
...
```
and do:

```shell
rm -rf /path/to/download-cache/dist/plone.recipe.codeanalysis-*
rm -rf /path/to/eggs-directory/eggs/plone.recipe.codeanalysis-*
./bin/buildout
```
The result is:

	Develop: '/home/user/sites/mysite/zeocluster/src/myproduct/.'
	Getting distribution for 'plone.recipe.codeanalysis'.
	warning: no previously-included files matching '*.pyc' found anywhere in distribution
	Got plone.recipe.codeanalysis 1.1.1.
	Uninstalling code-analysis.
	Unused options for buildout: 'package-min-coverage'.
	Updating instance.
	Updating test.
	Installing code-analysis.
	Getting distribution for 'plone.recipe.codeanalysis'.
	warning: no previously-included files matching '*.pyc' found anywhere in distribution
	warning: no previously-included files matching '**/.DS_Store' found anywhere in distribution
	warning: no previously-included files matching '**/__pycache__' found anywhere in distribution
	Got plone.recipe.codeanalysis 2.0b1.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/flake8'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-flake8'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-jshint'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-jscs'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-csslint'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-zptlint'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-deprecated-aliases'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-utf8-header'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-clean-lines'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-prefer-single-quotes'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-pep3101'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-imports'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-debug-statements'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-find-untranslated'.
	Generated script '/home/user/sites/mysite/zeocluster/src/myproduct/bin/code-analysis-hasattr'.
	Unable to create git pre-commit hook, this does not seem to be a git repository.
	Updating omelette.
	omelette: (While processing egg setuptools) Package 'easy_install' is zipped.  Skipping.
	omelette: (While processing egg setuptools) Package 'pkg_resources' is zipped.  Skipping.
	omelette: (While processing egg setuptools) Package 'setuptools' is zipped.  Skipping.
	omelette: (While processing egg setuptools) Package 'site' is zipped.  Skipping.
	Updating node.

That is, it continues downloading both versions.

And when I did not pin, I'm just wanting the buildout download the latest version.

**Comment by idgserpro** [comment]
@hvelarde and if this is not fix in buildout.plonetest, everyone who does not realize will have the above error.

**Comment by idgserpro** [comment]
related with: https://github.com/plone/plone.recipe.codeanalysis/issues/116

**Comment by hvelarde** [comment]
I just tested and, even when it downloads both versions, it uses 2.0b1:

```bash
# grep codeanalysis bin/code-analysis
    '/home/hvelarde/.buildout/eggs/plone.recipe.codeanalysis-2.0b1-py2.7.egg',
import plone.recipe.codeanalysis
    sys.exit(plone.recipe.codeanalysis.code_analysis({'_d': '/home/hvelarde/collective/upload/develop-eggs', 'jshint-exclude': '', 'deprecated-aliases': 'False', 'imports': 'False', 'flake8-exclude': 'bootstrap.py,boostrap-buildout.py,docs,*.egg', 'recipe': 'plone.recipe.codeanalysis', 'find-untranslated': 'False', 'zptlint': 'False', 'flake8-max-complexity': '12', 'jshint': 'True', 'csslint-bin': 'bin/csslint', 'clean-lines-exclude': '', 'i18ndude-bin': '', 'utf8-header': 'False', 'executable': '/home/hvelarde/collective/buildout.python/python-2.7/bin/python', 'eggs-directory': '/home/hvelarde/.buildout/eggs', 'prefer-single-quotes': 'False', 'jshint-bin': 'bin/jshint', 'location': '/home/hvelarde/collective/upload/parts/code-analysis', 'debug-statements': 'False', '_e': '/home/hvelarde/.buildout/eggs', 'jscs-bin': 'jscs', '_b': '/home/hvelarde/collective/upload/bin', 'flake8': 'True', 'bin-directory': '/home/hvelarde/collective/upload/bin', 'jscs-exclude': '', 'pep3101': 'False', 'pre-commit-hook': 'True', 'python': 'buildout', 'find-links': 'http://dist.plone.org/release/4.3-latest/\nhttp://dist.plone.org/thirdparty/', 'string-formatting': 'False', 'return-status-codes': 'True', 'flake8-max-line-length': '79', 'clean-lines': 'False', 'hasattr': 'False', 'csslint': 'True', 'jscs': 'False', 'deprecated-alias': 'False', 'develop-eggs-directory': '/home/hvelarde/collective/upload/develop-eggs', 'flake8-ignore': 'E501', 'deprecated-methods': 'False', 'zptlint-bin': '', 'jenkins': 'False', 'directory': '/home/hvelarde/collective/upload/src/collective/upload', 'flake8-filesystem': 'False'}))
```

**Comment by idgserpro** [comment]
It is used version 2.0b1 in sys.path but the installed recipe is the version 1.1.1. The script bin/code-analysis works because the method used (```plone.recipe.codeanalysis.code_analysis```) is the same in both versions. But, for example, the script bin/code-analysis-clean-line does not use the same method in both versions, an error occurring. [Read](#issue-93283866).

**Comment by idgserpro** [comment]
@saily  you can help here?

**Comment by saily** [comment]
thats because the old script still exists and bin/ directory is not cleaned up. if you start from scratch the file would not have been created.

**Comment by idgserpro** [comment]
@saily even removing the file bin/code-analysis-clean-line and run the buildout again it will create the script bin/code-analysis-clean-line if I use the option:

```
clean-lines = True
```
And when I run bin/code-analysis-clean-line, I get the error:

```
AttributeError: 'module' object has no attribute 'code_analysis_clean_lines'
```
This also occurs with scrit bin/code-analysis-flake8

See: https://github.com/plone/plone.recipe.codeanalysis/issues/116

**Comment by saily** [comment]
set `prefer-final= false` in your buildout an try again.

**Comment by idgserpro** [comment]
I tested the ```prefer-final = false``` and it didn't work with the zc.buildout 1.7.1. The error continues to occur with scripts ```bin/code-analysis-flake8``` and ```bin/code-analysis-clean-lines```. The zc.buildout 1.7.1 is the version used in [buildout.plonetest for Plone 4](http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg) and is the version that [Plone 4 is tested](http://jenkins.plone.org/job/plone-4.3-python-2.7/ws/bin/jenkins-alltests/*view*/). The only option that worked as zc.buildout 1.7.1 was:

```accept-buildout-test-releases = true```

You could test this when plone.recipe.codeanalysis is not pinned?

**Comment by idgserpro** [comment]
@hvelarde you can also test?

**Comment by hvelarde** [comment]
@idgserpro seems like a bug in zc.buildout; don't use v1.7.1, but latest:

```bash
# bin/buildout 
/home/hvelarde/.buildout/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Upgraded:
  zc.buildout version 2.4.0;
restarting.
Generated script '/home/hvelarde/collective/upload/bin/buildout'.
Develop: '/home/hvelarde/collective/upload/.'
Getting distribution for 'plone.recipe.codeanalysis'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '**/.DS_Store' found anywhere in distribution
warning: no previously-included files matching '**/__pycache__' found anywhere in distribution
Got plone.recipe.codeanalysis 2.0b1.
Unused options for buildout: 'package-min-coverage' 'unzip'.
Installing instance.
/home/hvelarde/.buildout/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Generated script '/home/hvelarde/collective/upload/bin/instance'.
Generated interpreter '/home/hvelarde/collective/upload/parts/instance/bin/interpreter'.
Installing test.
Generated script '/home/hvelarde/collective/upload/bin/test'.
Installing code-analysis.
Generated script '/home/hvelarde/collective/upload/bin/flake8'.
Generated script '/home/hvelarde/collective/upload/bin/check-manifest'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-csslint'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-check-manifest'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-clean-lines'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-debug-statements'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-deprecated-aliases'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-flake8'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-hasattr'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-find-untranslated'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-imports'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-jscs'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-jshint'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-pep3101'.
Generated script '/home/hvelarde/collective/upload/bin/code-analysis-zptlint'.
Unable to create git pre-commit hook, this does not seem to be a git repository.
# ls bin/code-analysis*
bin/code-analysis                 bin/code-analysis-csslint             bin/code-analysis-find-untranslated  bin/code-analysis-imports  bin/code-analysis-pep3101
bin/code-analysis-check-manifest  bin/code-analysis-debug-statements    bin/code-analysis-flake8             bin/code-analysis-jscs     bin/code-analysis-zptlint
bin/code-analysis-clean-lines     bin/code-analysis-deprecated-aliases  bin/code-analysis-hasattr            bin/code-analysis-jshint
```

**Comment by idgserpro** [comment]
@hvelarde  yes. It seems to be a problem of the zc.buildout 1.7.1. However, the Plone 4 uses the zc.bulidout 1.7.1 [in their tests](http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg) and I think that us should use the same version. And many packages that use buildout.plonetest don't pining the zc.bulidout. So this problem should be occurring in many packages. Using the ```accept-buildout-test = true``` option releases the problem no longer occurs with the zc.buildout 1.7.1. So my suggestion is to add this option to buildout.plonetest. This would save a lot of headaches for those who have not realized the problem.

The plone.recipe.codeanalysis is just one example. The problem may occur in other recipes as well.

**Comment by hvelarde** [comment]
@idgserpro then use `accept-buildout-test-releases = true` in your builds :-)

IMO, this is not a solution but a hack as that option is not intended to do what you want to do; from zc.buildout 1.5.0 changelog:

_By default, Buildout and the bootstrap script now prefer final versions of Buildout, recipes, and extensions. This can be changed by using the –accept-buildout-test-releases flag (or -t for short) when calling bootstrap. This will hopefully allow beta releases of these items to be more easily and safely made in the future._

_**NOTE: dependencies of your own software are not affected by this new behavior. Buildout continues to choose the newest available versions of your dependencies regardless of whether they are final releases.** To prevent this, use the pre-existing switch prefer-final = true in the [buildout] section of your configuration file (see http://pypi.python.org/pypi/zc.buildout#preferring-final-releases) or pin your versions using a versions section (see http://pypi.python.org/pypi/zc.buildout#repeatable-buildouts-controlling-eggs-used)._

**Comment by idgserpro** [comment]
@hvelarde that's exactly what I want. When I use:

```
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg
    https://raw.github.com/plone/plone.app.robotframework/master/versions.cfg

accept-buildout-test-releases = true
...

```

everything works fine. I'll put in my packages so.
