### ISSUE TITLE
Add section i18ndude in qc.cfg

### ISSUE THREAD

**Issue by idgserpro** [collective/buildout.plonetest#17]
The [rebuild_i18n-sh section](https://github.com/collective/buildout.plonetest/blob/master/qa.cfg#L71) uses the i18ndude. It doesn't make sense to have the rebuild_i18n-sh section and not have the i18ndude section.

**Comment by idgserpro** [comment]
@hvelarde opinion?

**Comment by hvelarde** [comment]
I don't understand the issue; that part is there so you can include it if you want it.

**Comment by idgserpro** [comment]
If you have in buildout:

```properties
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg

parts +=
    rebuild_i18n-sh

...
```
the script rebuild_i18n-sh doesn't work because we do not have the bin/i18ndude. We would have to have:

```properties
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg

parts +=
    rebuild_i18n-sh
    i18ndude

[i18ndude]
recipe = zc.recipe.egg
eggs = i18ndude

...
```

The idea here is have the i18ndude session in qc.cfg not be necessary to add in all our buildout. Or better yet. The rebuild_i18n-sh session install egg i18ndude.

**Comment by hvelarde** [comment]
+1
