### ISSUE TITLE
Pin zc.recipe.cmmi to 1.3.6.

### ISSUE THREAD

**Issue by idgserpro** [collective/buildout.plonetest#25]
Since zc.recipe.cmmi 2.0.0 in 2017/06/21, it asks for the newest zc.buildout release and not all installations can afford that, so let's pin it to 1.3.6. This version asks for at least zc.buildout 1.4, but since                    http://dist.plone.org/release/4.0-latest/versions.cfg asks for 1.4.4, no harm done.

For more info:

https://community.plone.org/t/zc-recipe-cmmi-2-0-0-released-today-21-06-2017-will-break-all-buildouts-from-plone-because-it-asks-for-zc-buildout-2-9-4-how-should-we-behave/4412/

**Comment by hvelarde** [comment]
closed by #26
