### ISSUE TITLE
Improve rebuild_i18n-sh for plone-manual.pot entries?

### ISSUE THREAD

**Issue by idgserpro** [collective/buildout.plonetest#44]
In some projects you may have manual entries to plone translation msgids, specially if you're customizing some views. In this situation, it's normal to have a `plone-manual.pot` that is merged with the plone.pot that is rebuilt when you run i18ndude. Some examples:

https://github.com/collective/ecreall.trashcan/blob/a33a327d62e9502f15a0907a593e68747b74a6d6/ecreall/trashcan/locales/update.sh

https://github.com/plone/plone.app.workflowmanager/blob/01ef8f6c581e593eb146bd45ad291d3939d8ceb5/rebuild_i18n.sh

If you don't use the manual approach and want to translate something in the Plone namespace _and_ have a file in your package using `plone` domain, the `msgids` are removed from plone.pot, thus the need of a `plone-manual.pot`.

What do you think @mauritsvanrees? We can try adding this with a PR.

**Comment by mauritsvanrees** [comment]
I am getting confused with the recent issues and PRs here. I am recently back from a long vacation, maybe that explains. :-)

What I would expect the script to do for `pot` files:

- Create a `mydomain.pot` and merge it with `mydomain-manual.pot` if this exists (or just `manual.pot`, I haven't checked).
- Create a `plone.pot` and merge it with `plone-manual.pot` if it exists.

It is fine if any of these `pot` files are basically empty.

**Comment by idgserpro** [comment]
> I am getting confused with the recent issues and PRs here. I am recently back from a long vacation, maybe that explains. :-)

The last issue and PR were indeed bad examples. We've closed the PR and updated the issue with more information.

> What I would expect the script to do for pot files

This is our expectation as well, but rebuild_i18n-sh now just asks for a `manual.pot`. The idea is to add the same feature but for a `plone-manual.pot`.

I want to keep `manual.pot` for the sake of compatibility.

**Comment by idgserpro** [comment]
We'll try to add this in a new PR.
