### ISSUE TITLE
Endless loop with test-4.x.cfg 

### ISSUE THREAD

**Issue by htgoebel** [collective/buildout.plonetest#53]
When trying to install from this simple `travis.cfg`-file,
```
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.x.cfg
package-name = collective.blogging
```
installation ends in an endless loop:
```
$ bin/buildout -c travis.cfg
Upgraded:
  zc.buildout version 1.7.1,
  setuptools version 26.1.1;
restarting.
Upgraded:
  zc.buildout version 1.7.1,
  setuptools version 26.1.1;
restarting.
…
```

**How tp reproduce**
```
$ mkdir p4 ; cd p4
$ virtualenv -p `which python2.7` .
$ . bin/activate
$ python --version
Python 2.7.16
$ pip list
pip        19.3.1
setuptools 41.4.0
wheel      0.33.
$ pip install zc.buildout
$ bin/buildout -c travis.cfg
```

**Comment by htgoebel** [comment]
Addendum: When pinning versions as recommended in the README
```
[versions]
setuptools = 41.2.0
zc.buildout = 2.13.2
```
the endliess look changes to
```
Upgraded:
  setuptools version 41.2.0;
restarting.
…
```

**Comment by mauritsvanrees** [comment]
Try this:

    bin/buildout -c travis.cfg -N

That works for me with your example. (I have to set `develop =` to prevent further problems, but that is beside the point).
I often do that in travis configs, exactly to prevent this kind of problem.

**Comment by idgserpro** [comment]
@htgoebel before you run buildout, you need run:

```
./bin/pip install -r requirements.txt
```

with the `setuptools` and `zc.buildout` versions of Plone 4.3.

See an example of `requirements.txt` here: https://github.com/collective/minimalplone4/blob/master/requirements.txt

**Comment by htgoebel** [comment]
@mauritsvanrees 
- `-N` did the trick. How can we emphasis on this in the example? Add a comment to the example?

@idgserpro 
- The example does not talk about the content of `requirements.txt` and does not give any hint about this. Thus I assume this contains the "normal" requirements for the project. Also, to my understanding, this should not affect anything since the required versions are pinned in the x.x-latest/versions.cfg file.
* Using setuptools < 30.3.0 will fail to install `configparser`, see #54 
This this solution is to run buildout with `-N`.

**Comment by idgserpro** [comment]
@htgoebel each version of Plone must contain its `requirements-x.x.txt` with the same versions of `setuptools` and `zc.buildout` as `x.x-latest/versions.cfg`. This will not affect `x.x-latest/versions.cfg` versions, as they will be the same.

About `configparser`, it's best pin its version in the Plone 4.3 buidout.

**Comment by idgserpro** [comment]
@mauritsvanrees we think `configparser` should be pinned on Plone official cfgs. What do you think?

**Comment by htgoebel** [comment]
@idgserpro There is no need to pin configparser, and there is no need to sue a specific version of setuptools or zc.buildout.

Configparser is required by flask, not by Plone, thus pinning it would be counterproductive.

Having a newer version of setuptools and/ot zc.buildout installed is okay even for Plone 4.3: Both are used for downloading and installing packages. All scripts generated by buildout will use the version as pinned in the .cfg-file.

**Comment by idgserpro** [comment]
> The example does not talk about the content of requirements.txt and does not give any hint about this.

@htgoebel the content of `requirements.txt` is shown here:

https://github.com/collective/buildout.plonetest#testing-in-travis-ci-with-multiple-versions-of-plone-and-python

Do you still think that anything can be improved in the documentation or can we close the issue?

**Comment by htgoebel** [comment]
* Using `requirements.txt` does not solve the issue. Try will give you an endless loop:
```
virtualenv -p `which python2.7` p4
cd p4
bin/pip list

cat > requirements.txt <<EOF
setuptools==41.2.0
zc.buildout==2.13.2
EOF

cat > mytest.cfg <<EOF
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.x.cfg
package-name = collective.blogging
EOF

bin/pip install -r requirements.txt
#bin/pip install zc.buildout
bin/buildout -c mytest.cfg
```

* When trying the same as above, just with ``-N`` in the last line, installation failed with an unhandled exception.

* I was not able to reprocude my case from October: When using setuptools==26.1.1 and zc.buildout==1.7.1, buildout will fail with an AssertionError. (And when pinning pip and wheel, too, I got the same unhandled exception.

Looks like some external changes come in there. Giving up in this.

**Comment by idgserpro** [comment]
@htgoebel to work, you need two changes:

- Pin the same `setuptools/buildout` versions of `requirements.txt` in your cfg.
- Add `develop =` to your cfg to avoid buildout execution errors.

So stay:

```
virtualenv -p `which python2.7` p4
cd p4
bin/pip list

cat > requirements.txt <<EOF
setuptools==41.2.0
zc.buildout==2.13.2
EOF

cat > mytest.cfg <<EOF
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.x.cfg
package-name = collective.blogging
develop =
[versions]
setuptools=41.2.0
zc.buildout=2.13.2
EOF

bin/pip install -r requirements.txt
bin/buildout -c mytest.cfg
```
