### ISSUE TITLE
qa.cfg fails with test-4.x.cfg - using wrong version of configparser

### ISSUE THREAD

**Issue by htgoebel** [collective/buildout.plonetest#54]
When trying to install from this simple `travis.cfg`-file,
```
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg
package-name = collective.blogging
```
this fails with
```
Got flake8 3.3.0.
Getting distribution for 'check-manifest'.
Got check-manifest 0.40.
Getting distribution for 'configparser'.
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
backports.__init__: module references __path__
Installing configparser 4.0.2
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different project name.
Installing configparser 4.0.2
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different version.
Got None.
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis.
Error: There is a version conflict.
We already have: UNKNOWN 0.0.0
but flake8 3.3.0 requires 'configparser'.
```

**How tp reproduce**
```
$ mkdir p4 ; cd p4
$ virtualenv -p `which python2.7` .
$ . bin/activate
$ python --version
Python 2.7.16
# Work around https://github.com/collective/buildout.plonetest/issues/53
$ pip install --force-reinstall setuptools==26.1.1
$ pip install zc.buildout==1.7.1
$ bin/buildout -c travis.cfg
```

When removing the `qa.cfg` line, buildout passes (but qa parts are missing, of course).

**Analyzes**

This seems to be caused be `configparser` requiring a newer version for `setuptool`, which is able to read metadata from `setup.cfg`. In [version 3.5.3 setup.py](https://github.com/jaraco/configparser/blob/3.5.3/setup.py) is the last version where the metadata included in `setup.py`.

**Possibe solution**

Add this to `qa.cfg`
```
[versions]
configparser=3.5.3
```

This might affect other versions, too if setuptools is pinned to some [setuptools version < 30.3.0 (8 Dec 2016)][https://setuptools.readthedocs.io/en/latest/setuptools.html#id51]

**Comment by mauritsvanrees** [comment]
This would pin `configparser` to a low version for all buildouts, including buildouts with a more recent `setuptools` that could handle newer versions just fine.

It is probably better to pin newer versions of setuptools and zc.buildout.

**Comment by htgoebel** [comment]
New insights: When running `buildout` with `-N`, this issue does not occur (at least if the setuptools installed in the virtual environment is >= 30.3.0).

Thus no pinning is required at all. One only needs to ensure the setuptools in the virtualenv is somewhat current and `-N` is used.

**Comment by htgoebel** [comment]
For the records:
**Solution**
- Update setuptools in the virutal environment.
   (Or more sustainable: Update `virtualenv` package and refresh this virtual environment-)
- Run `buildout` with `-N`.
