### ISSUE TITLE
assert newdist is not None  # newloc above is missing our dist?!

### ISSUE THREAD

**Issue by idgserpro** [collective/buildout.plonetest#60]
When I use `bootstrap.py` on Plone 5 with a python without `setuptools`, the following error occurs if the cache is empty:

```bash
While:
  Installing.
  Getting section code-analysis.
  Initializing section code-analysis.
  Installing recipe plone.recipe.codeanalysis[recommended].
  Getting distribution for 'configparser'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1388, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/user/cache-python/eggs2/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 1776, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError
```

This is because of the use of  `newest = false` made in PR #37. When we run buildout, the `setuptools` aren't updated, and is used version 33.1.1, "pinned" by `ez_setup.py`, and not the Plone 5 version. `configparser` requires newer versions of setuptools, giving the error.

Steps to reproduce:

```bash
git clone https://github.com/collective/collective.cover
cd collective.cover
vi buildout.cfg
# Change to Plone 5.1 in extends
virtualenv --no-setuptools .
./bin/python bootstrap.py
# simulate empty cache
./bin/buildout buildout:eggs-directory=/tmp/eggs buildout:download-cache=/tmp/downloads
```

I think we should not use `newer = false`

@mauritsvanrees @hvelarde

**Comment by mauritsvanrees** [comment]
You shouldn't use `bootstrap.py`, but `bin/pip install requirements.txt` and have a recent enough setuptools in those requirements.
Or specify a newer setuptools in the bootstrap call, for example:

    bin/python bootstrap.py --setuptools-version=40.8.0

The problem with `newest = true` is that this may lead to infinite restarts of buildout as it gets new versions that somehow do not 'stick' in the `bin/buildout` script. (I still don't know why that happens.)

**Comment by idgserpro** [comment]
> You shouldn't use bootstrap.py, but bin/pip install requirements.txt

Yes, I know that pip works (although I prefer bootstrap.py).  @hvelarde, can we replace bootstrap.py by pip, in packages that use bootstrap.py?

> The problem with newest = true is that this may lead to infinite restarts of buildout as it gets new versions that somehow do not 'stick' in the bin/buildout script. (I still don't know why that happens.)

The restart only occurs if the versions of setuptools/zc.buildout of python are different from the buildout pinned versions. If you use pip to install buildout and the versions of setuptools/zc.buildout in requirements.txt are the same as pinned in buildout, you have no restarting problem, even with "newest = true".

`newest = false` helps in situations where bootstrap.py is used and python's setuptools/zc.buildout versions are different from the pinned versions in buildout. This is why I run bootstrap.py with python without setuptools. When we don't have setuptools in python, the restart problem doesn't occur either.

Below is an example where restart does not occur, even with `newest = true`:

```bash
git clone https://github.com/collective/collective.cover
cd collective.cover
vi buildout.cfg
# Change to Plone 5.1 in extends and change newest to true
vi requirements.txt
# Create requirments.txt with the same versions as 5.1-latest:
# setuptools==40.8.0
# zc.buildout==2.13.1
virtualenv .
./bin/pip install -r requirements.txt
# simulate empty cache
./bin/buildout buildout:eggs-directory=/tmp/eggs buildout:download-cache=/tmp/downloads
```
